language: node_js
node_js:
  - lts/*
  - 13.9.0 # 13.10.X must be disabled due to node#32184
services:
  - postgresql
before_install:
  - psql -c "ALTER USER postgres PASSWORD 'postgres';" -U postgres
cache:
  yarn: true
  directories:
    - "node_modules"
script:
  - yarn lint
  - yarn demo:build
  - yarn test:cov
after_success:
  - yarn cov:merge
  - yarn coveralls
